// Opening-name lookups from a bundled database — instant, offline, no API, no
// token. The data in openings-data.json is generated by scripts/build-openings.mjs
// from the openly-licensed lichess-org/chess-openings dataset (CC0): every known
// opening position keyed by the first four fields of its FEN (board, side to
// move, castling, en-passant). The app computes the identical key at runtime, so
// a lookup is just an object access.
//
// NOTE: this is for NAMING ONLY. Move grading (best/good/inaccuracy/mistake/
// blunder) lives entirely in engine.ts and is untouched by any of this.

import data from './openings-data.json';

const NAMES = data as Record<string, string>;

// The position key shared with the build script: first four FEN fields, dropping
// the halfmove/fullmove clocks (they never affect the opening name). chess.js
// only sets the en-passant square when a capture is genuinely available, so the
// raw FEN matches the dataset without any normalisation.
function epdKey(fen: string): string {
  return fen.split(' ').slice(0, 4).join(' ');
}

/** The opening name for a single position FEN, or null if it isn't a named one. */
export function nameForFen(fen: string): string | null {
  return NAMES[epdKey(fen)] ?? null;
}

/**
 * The best opening name for a line, given the FENs of each position along it in
 * order. Scans from the deepest position back to the first and returns the first
 * named match — so a line that runs past known theory still shows the name of
 * the deepest position the database recognises.
 */
export function nameForPath(fens: string[]): string | null {
  for (let i = fens.length - 1; i >= 0; i--) {
    const name = nameForFen(fens[i]);
    if (name) return name;
  }
  return null;
}

// ── "Out of book" detection (for engine sparring) ────────────────────────────
// The database names only the *terminal* position of each known line, so legal
// theory has short unnamed gaps mid-sequence (e.g. the Ruy Lopez names a6 and
// O-O but not the Ba4/Nf6 between them). We therefore declare a line "out of
// book" only after several consecutive unnamed half-moves: that never triggers
// inside known theory yet latches reliably once theory genuinely ends.
export const BOOK_GAP_TOLERANCE = 3;

// Deepest half-move (1-based) along `fens` that the book recognises, or 0.
function deepestNamedPly(fens: string[]): number {
  let last = 0;
  for (let i = 0; i < fens.length; i++) if (nameForFen(fens[i])) last = i + 1;
  return last;
}

/**
 * True once a line has run far enough past its deepest named position to count
 * as off-book. A pure function of the positions played, so callers can recompute
 * it freely (e.g. after an undo).
 */
export function isOutOfBook(fens: string[]): boolean {
  if (fens.length === 0) return false;
  return fens.length - deepestNamedPly(fens) >= BOOK_GAP_TOLERANCE;
}
